---
hero_image: images/wheres-the-treasure.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Waar is de schat?
description: Onthoud waar de munt verborgen is
original_url: https://codeclubprojects.org/en-GB/sense-hat/wheres-the-treasure
interests: games
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: 'Inleiding: '
- title: De schat verbergen
- title: De schat vinden
  completion:
  - engaged
- title: Score bijhouden
  completion:
  - internal
- title: 'Uitdaging: het spel aanpassen'
- title: 'Uitdaging: maak het moeilijker'
