---
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Where's the Treasure?
description: Remember where the coin is hidden
original_url: https://codeclubprojects.org/en-GB/sense-hat/wheres-the-treasure
interests: ''
technologies: sense-hat
site_areas: codeclub, sense-hat
steps:
- title: 'Introduction: '
- title: Hiding the treasure
- title: Finding the treasure
- title: Keeping score
- title: 'Challenge: Customize the game'
- title: 'Challenge: Make it harder'

