---
hero_image: images/wheres-the-treasure.png
theme: gul
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmering-1, phys-comp-0, tillverkning-0, community-0
title: Where's the Treasure?
description: Remember where the coin is hidden
original_url: https://codeclubprojects.org/en-GB/sense-hat/wheres-the-treasure
interests: spel
technologies: sense-hat
site_areas: projekt
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Introduktion: '
  - 
    title: Hiding the treasure
  - 
    title: Finding the treasure
  - 
    title: Keeping score
  - 
    title: 'Challenge: Customize the game'
  - 
    title: 'Challenge: Make it harder'
