---
hero_image: images/wheres-the-treasure.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmation-1, phys-comp-0, fabrication-0, communauté-0
title: Where's the Treasure?
description: Remember where the coin is hidden
original_url: https://codeclubprojects.org/en-GB/sense-hat/wheres-the-treasure
interests: games
technologies: sense-hat
site_areas: projets
hardware: sense-hat
software: ''
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: 'Introduction'
  - 
    title: Hiding the treasure
  - 
    title: Finding the treasure
  - 
    title: Keeping score
  - 
    title: 'Challenge: Customize the game'
  - 
    title: 'Challenge: Make it harder'
