---
hero_image: images/wheres-the-treasure.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Où est le trésor ?
description: Rappelle-toi où la pièce est cachée
original_url: https://codeclubprojects.org/en-GB/sense-hat/wheres-the-treasure
interests: games
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Cacher le trésor
- title: Découvrir le trésor
  completion:
  - engaged
- title: Conserver le score
  completion:
  - internal
- title: 'Défi : personnaliser le jeu'
- title: 'Défi : Rends-le plus difficile'
